### PR TITLE
Adding UIImage extension to create images out of icons.  refactor UIT…

### PR DESCRIPTION
**Pull request by jacobbullock**
This is a simple refactor of code you already had written for UITabBarItem.  It exposes that method to a UIImage Category so it is more reusable. 

This should be updated to add more features like a background color or something like that later.

### CODE REVIEW

**Comment by jacobbullock** [comment]
This PR also makes the extensions for UIBarButtonItem and UITabBarItem public, which is in a separate issue i logged earlier today.

**Comment by 0x73** [comment]
Thanks.

**Comment by otymartin** [comment]
@jacobbullock 
I found it impossible to center an Icon Image on the left of the Button Title.

**Comment by jacobbullock** [comment]
@otymartin i'll take a look

**Comment by jacobbullock** [comment]
@otymartin can you describe the issue you are having.  Are you wanting the image + text to be centered?  Because the category here simply creates a UIImage from text and centers it in the frame. So if you are having alignment issues you may want to try titleEdgeInsets or something along those lines.

**Pull request merged**
